---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: beka
spec:
  selector:
    matchLabels:
      app: beka
  template:
    metadata:
      labels:
        app: beka
    spec:
      containers:
      - name: beka
        image: nginx:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "echo 'BEKA' > /usr/share/nginx/html/index.html"]

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nur
spec:
  selector:
    matchLabels:
      app: nur
  template:
    metadata:
      labels:
        app: nur
    spec:
      containers:
      - name: nur
        image: nginx:latest
        imagePullPolicy: Always
        lifecycle:
          postStart:
            exec:
              command: ["/bin/bash", "-c", "echo 'NURMUKHAMMED' > /usr/share/nginx/html/index.html"]

---
apiVersion: v1
kind: Service
metadata:
  name: beka-service
  labels:
    app: beka
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: beka

---
apiVersion: v1
kind: Service
metadata:
  name: nur-service
  labels:
    app: nur
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    name: http
  selector:
    app: nur


